version: '2'
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:2.5
    ports:
      - '2181:2181'
      - '2888:2888'
      - '3888:3888'
  kafka:
    image: quay.io/debezium/kafka:2.5
    ports:
      - '9092:9092'
      - '29092:29092'
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_LISTENERS=INSIDE://:29092,OUTSIDE://:9092
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://:29092,OUTSIDE://${KAFKA_OUTSIDE_HOST}:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
  connect:
    image: quay.io/debezium/connect:2.5
    ports:
      - '8083:8083'
    links:
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=kafka:29092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
  meilisync:
    image: nullmastermind/meili-sync-image:latest
    links:
      - connect
    environment:
      - CONNECT_SERVER=connect:8083
      - KAFKA_OUTSIDE_HOST=${KAFKA_OUTSIDE_HOST}
    volumes:
      - ./configs.json:/app/configs.json
